# Generated by Django 5.1.6 on 2025-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
