# Generated by Django 5.1.6 on 2025-03-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_entry_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='no_of_invoices',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
