# Generated by Django 5.1.6 on 2025-03-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_entry_no_of_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
