# Generated by Django 5.1.6 on 2025-04-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_vehicle_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
