# Generated by Django 5.1.6 on 2025-04-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_invoice_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
