# Generated by Django 5.1.6 on 2025-04-08 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_invoice_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.party'),
        ),
    ]
